version: '3.3'

services:
  webserver:
    image: nginx:alpine
    restart: always
    container_name: manchadetinta-nginx
    working_dir: /src
    volumes:
      - ./:/src
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  php-fpm:
    build: .docker/php-fpm
    restart: always
    container_name: manchadetinta_php74
    working_dir: /src
    expose:
      - 9000
    volumes:
      - ./:/src

  database:
    container_name: manchadetinta_db
    build: .docker/db
    volumes:
      - db-volume:/var/lib/mysql
    ports: 
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 2YT3DbaENpT9uoRByR
      MYSQL_DATABASE: theinkstain
      MYSQL_USER: manchinha2020
      MYSQL_PASSWORD: 2YT3DbaENpT9uoRByR
    restart: always  
volumes:
    db-volume:
